version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: CQRSPattern.Api/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__ReadDb=Server=db;Database=CQRSPatternRead;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
      - ConnectionStrings__WriteDb=Server=db;Database=CQRSPatternWrite;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - cqrs-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - cqrs-network

networks:
  cqrs-network:
    driver: bridge

volumes:
  db-data: